---
name:         Tk-Airports
version:      0.05
version_from: lib/Tk/Airports.pm
installdirs:  site
requires:
    Tk:                            804.027
    Tk::HList:                     0
    Tk::Toplevel:                  0
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
license: perl
